yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: "node-modules"

unsafeHttpWhitelist:
  - localhost
  - 3.89.41.88

npmRegistries:
  "http://3.89.41.88:4873/":
    npmAlwaysAuth: true
    npmAuthToken: CgcjMOa2QyMunSLr9YDzUA==
npmScopes:
  eventdex:
    npmRegistryServer: http://3.89.41.88:4873
    npmPublishRegistry: http://3.89.41.88:4873
